export const indianStates = [
  'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh',
  'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand', 'Karnataka',
  'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram',
  'Nagaland', 'Odisha', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu',
  'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal',
  'Andaman and Nicobar Islands', 'Chandigarh', 'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi', 'Jammu and Kashmir', 'Ladakh', 'Lakshadweep', 'Puducherry'
];

export const educationLevels = [
  { value: 'no_formal', labelKey: 'noFormalEducation' },
  { value: 'primary', labelKey: 'primarySchool' },
  { value: 'secondary', labelKey: 'secondarySchool' },
  { value: 'higher_secondary', labelKey: 'higherSecondary' },
  { value: 'diploma', labelKey: 'diploma' },
  { value: 'graduate', labelKey: 'graduate' },
  { value: 'post_graduate', labelKey: 'postGraduate' },
  { value: 'other', labelKey: 'other' },
];

// Jharkhand local languages + Hindi, English, Bangla
export const languageOptions = [
  { value: 'hindi', labelKey: 'hindi' },
  { value: 'english', labelKey: 'english' },
  { value: 'bangla', labelKey: 'bangla' },
  { value: 'santali', labelKey: 'santali' },
  { value: 'mundari', labelKey: 'mundari' },
  { value: 'ho', labelKey: 'ho' },
  { value: 'kurukh', labelKey: 'kurukh' },
  { value: 'nagpuri', labelKey: 'nagpuri' },
  { value: 'khortha', labelKey: 'khortha' },
  { value: 'kurmali', labelKey: 'kurmali' },
  { value: 'panchPargania', labelKey: 'panchPargania' },
  { value: 'other', labelKey: 'other' },
];

export const experienceGroups = [
  { value: '1-5', label: '1–5 years' },
  { value: '6-8', label: '6–8 years' },
  { value: '9-10', label: '9–10 years' },
  { value: '11-15', label: '11–15 years' },
  { value: '16-20', label: '16–20 years' },
  { value: '20+', label: '20+ years' },
];

export const workModes = [
  { value: 'daily_wage', labelKey: 'dailyWage' },
  { value: 'monthly_salary', labelKey: 'monthlySalary' },
  { value: 'piece_rate', labelKey: 'pieceRate' },
  { value: 'contract', labelKey: 'contract' },
  { value: 'self_employed', labelKey: 'selfEmployed' },
];

export const paymentModes = [
  { value: 'cash', labelKey: 'cash' },
  { value: 'bank_transfer', labelKey: 'bankTransfer' },
  { value: 'upi', labelKey: 'upi' },
  { value: 'cheque', labelKey: 'cheque' },
  { value: 'mixed', labelKey: 'mixed' },
];

export const challengeOptions = [
  { value: 'irregular_income', labelKey: 'irregularIncome' },
  { value: 'no_benefits', labelKey: 'noBenefits' },
  { value: 'unsafe_conditions', labelKey: 'unsafeConditions' },
  { value: 'no_job_security', labelKey: 'noJobSecurity' },
  { value: 'discrimination', labelKey: 'discrimination' },
  { value: 'lack_of_skills', labelKey: 'lackOfSkills' },
  { value: 'transportation', labelKey: 'transportation' },
  { value: 'other', labelKey: 'other' },
];

// Primary categories
export const primaryCategories = [
  { value: 'home_services', label: 'Home Services' },
  { value: 'personal_care', label: 'Personal Care' },
  { value: 'delivery_logistics', label: 'Delivery & Logistics' },
  { value: 'repair_technical', label: 'Repair & Technical Services' },
  { value: 'construction_trades', label: 'Construction & Skilled Trades' },
  { value: 'skilled_freelancers', label: 'Skilled Freelancers' },
  { value: 'retail_store', label: 'Retail & Store Work' },
  { value: 'hospitality_events', label: 'Hospitality & Event Services' },
  { value: 'manufacturing_factory', label: 'Manufacturing & Factory Work' },
  { value: 'security_services', label: 'Security Services' },
  { value: 'domestic_household', label: 'Domestic & Household Work' },
  { value: 'vehicle_services', label: 'Vehicle Services' },
  { value: 'others', label: 'Others' },
];

// Sub-categories mapped by primary category value
export const subCategoriesByPrimary: Record<string, string[]> = {
  home_services: [
    'Electrician',
    'Plumber',
    'Carpenter',
    'Painter (Home)',
    'AC Technician',
    'RO / Water Purifier Technician',
    'Pest Control Worker',
    'CCTV Installer',
    'Appliance Installation Technician',
    'Sofa / Carpet Cleaning Worker',
    'Tiles / Marble Polishing Worker',
    'Interior Work Helper',
    'Other (Specify)',
  ],
  personal_care: [
    'Beautician (Home Service)',
    'Salon Hair Stylist',
    'Makeup Artist',
    'Mehendi Artist',
    'Massage Therapist',
    'Spa Therapist',
    'Barber',
    'Nail Technician',
    'Fitness Trainer',
    'Yoga Instructor',
    'Babysitter / Nanny',
    'Elderly Caregiver',
    'Other (Specify)',
  ],
  delivery_logistics: [
    'Food Delivery Partner',
    'Grocery Delivery',
    'Courier Delivery',
    'E-commerce Delivery',
    'Bike Taxi Rider',
    'Auto Driver',
    'Cab Driver',
    'Truck Driver',
    'Tempo / Mini Truck Driver',
    'Warehouse Picker',
    'Warehouse Packer',
    'Loader / Unloader',
    'Last-Mile Delivery Agent',
    'Other (Specify)',
  ],
  repair_technical: [
    'Mobile Repair Technician',
    'Laptop / Desktop Repair',
    'TV Repair Technician',
    'Refrigerator Repair',
    'Washing Machine Repair',
    'Microwave Repair',
    'Geyser Repair',
    'Bike Mechanic',
    'Car Mechanic',
    'Generator Technician',
    'Inverter Technician',
    'Hardware Repair Technician',
    'Other (Specify)',
  ],
  construction_trades: [
    'Mason',
    'Construction Helper / Labour',
    'Tile Worker',
    'Welder',
    'Bar Bender',
    'Electric Line Worker',
    'Plaster Worker',
    'Scaffolding Worker',
    'Roofing Worker',
    'Painter (Construction)',
    'Excavator Operator',
    'Site Supervisor',
    'Contractor',
    'Other (Specify)',
  ],
  skilled_freelancers: [
    'Photographer',
    'Videographer',
    'Graphic Designer',
    'Social Media Manager',
    'Content Writer',
    'Data Entry Operator',
    'Event Coordinator',
    'DJ / Sound Technician',
    'Decorator',
    'Translator',
    'Other (Specify)',
  ],
  retail_store: [
    'Sales Assistant',
    'Store Helper',
    'Cashier',
    'Inventory Handler',
    'Mall Kiosk Worker',
    'Brand Promoter',
    'Other (Specify)',
  ],
  hospitality_events: [
    'Waiter / Server',
    'Cook / Chef',
    'Catering Helper',
    'Event Setup Worker',
    'Housekeeping Staff (Hotel)',
    'Banquet Staff',
    'Bartender',
    'Event Security',
    'Other (Specify)',
  ],
  manufacturing_factory: [
    'Machine Operator',
    'Assembly Line Worker',
    'Packaging Worker',
    'Quality Checker',
    'Fabrication Worker',
    'Textile Worker',
    'Printing Press Worker',
    'Other (Specify)',
  ],
  security_services: [
    'Security Guard',
    'Bouncer',
    'Night Watchman',
    'Gated Community Guard',
    'ATM Guard',
    'Other (Specify)',
  ],
  domestic_household: [
    'Full-Time Domestic Helper',
    'Part-Time Maid',
    'Household Cook',
    'Personal Driver',
    'Caretaker',
    'Live-in Domestic Worker',
    'Other (Specify)',
  ],
  vehicle_services: [
    'Car Washer',
    'Vehicle Painter',
    'Tyre Repair Worker',
    'Fuel Station Attendant',
    'Vehicle Cleaner',
    'Other (Specify)',
  ],
  others: [
    'Street Vendor',
    'Tailor',
    'Cobbler',
    'Scrap Collector',
    'Factory Helper',
    'Agricultural Helper',
    'Other (Specify)',
  ],
};

export const primaryWorkLocationOptions = [
  "At customer's home",
  'On-site (construction/site)',
  'Shop/Store',
  'Factory',
  'On road / Delivery',
  "Employer's house",
  'Multiple locations',
  'Other (Specify)',
];
