/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Category = IDL.Variant({
  'banking' : IDL.Null,
  'aadhaar' : IDL.Null,
  'insurance' : IDL.Null,
});
export const OTPStatus = IDL.Variant({
  'verified' : IDL.Null,
  'expired' : IDL.Null,
  'pending' : IDL.Null,
});
export const Survey = IDL.Record({
  'id' : IDL.Text,
  'age' : IDL.Nat,
  'otp' : IDL.Text,
  'modeOfPayment' : IDL.Text,
  'insuranceType' : IDL.Opt(IDL.Text),
  'digitalSignature' : IDL.Opt(ExternalBlob),
  'yearsOfExperienceGroup' : IDL.Text,
  'panchayat' : IDL.Text,
  'servingArea' : IDL.Opt(IDL.Text),
  'servingCity' : IDL.Opt(IDL.Text),
  'employerName' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
  'category' : Category,
  'aadhaarHash' : IDL.Opt(IDL.Text),
  'block' : IDL.Text,
  'servingPincode' : IDL.Opt(IDL.Text),
  'phoneNumber' : IDL.Text,
  'otpStatus' : OTPStatus,
  'servingPanchayat' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const OTPAttempt = IDL.Record({
  'timestamp' : IDL.Int,
  'success' : IDL.Bool,
  'phoneNumber' : IDL.Text,
});
export const SMSPayload = IDL.Record({
  'messageType' : IDL.Variant({ 'otp' : IDL.Null, 'confirmation' : IDL.Null }),
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phoneNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'exportSurveyData' : IDL.Func([], [IDL.Vec(Survey)], ['query']),
  'generateOTP' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAllSurveys' : IDL.Func([], [IDL.Vec(Survey)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategoryAnalytics' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Category, IDL.Nat))],
      ['query'],
    ),
  'getCompletionStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'total' : IDL.Nat,
          'rate' : IDL.Float64,
          'completed' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getOTPLogs' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(OTPAttempt)],
      ['query'],
    ),
  'getSMSPayloads' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(SMSPayload)],
      ['query'],
    ),
  'getSurvey' : IDL.Func([IDL.Text], [Survey], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVerificationStats' : IDL.Func(
      [],
      [IDL.Record({ 'verified' : IDL.Nat, 'unverified' : IDL.Nat })],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitSurvey' : IDL.Func([Survey], [], []),
  'verifyOTP' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Category = IDL.Variant({
    'banking' : IDL.Null,
    'aadhaar' : IDL.Null,
    'insurance' : IDL.Null,
  });
  const OTPStatus = IDL.Variant({
    'verified' : IDL.Null,
    'expired' : IDL.Null,
    'pending' : IDL.Null,
  });
  const Survey = IDL.Record({
    'id' : IDL.Text,
    'age' : IDL.Nat,
    'otp' : IDL.Text,
    'modeOfPayment' : IDL.Text,
    'insuranceType' : IDL.Opt(IDL.Text),
    'digitalSignature' : IDL.Opt(ExternalBlob),
    'yearsOfExperienceGroup' : IDL.Text,
    'panchayat' : IDL.Text,
    'servingArea' : IDL.Opt(IDL.Text),
    'servingCity' : IDL.Opt(IDL.Text),
    'employerName' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
    'category' : Category,
    'aadhaarHash' : IDL.Opt(IDL.Text),
    'block' : IDL.Text,
    'servingPincode' : IDL.Opt(IDL.Text),
    'phoneNumber' : IDL.Text,
    'otpStatus' : OTPStatus,
    'servingPanchayat' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const OTPAttempt = IDL.Record({
    'timestamp' : IDL.Int,
    'success' : IDL.Bool,
    'phoneNumber' : IDL.Text,
  });
  const SMSPayload = IDL.Record({
    'messageType' : IDL.Variant({
      'otp' : IDL.Null,
      'confirmation' : IDL.Null,
    }),
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phoneNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'exportSurveyData' : IDL.Func([], [IDL.Vec(Survey)], ['query']),
    'generateOTP' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAllSurveys' : IDL.Func([], [IDL.Vec(Survey)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategoryAnalytics' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Category, IDL.Nat))],
        ['query'],
      ),
    'getCompletionStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'total' : IDL.Nat,
            'rate' : IDL.Float64,
            'completed' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getOTPLogs' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(OTPAttempt)],
        ['query'],
      ),
    'getSMSPayloads' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(SMSPayload)],
        ['query'],
      ),
    'getSurvey' : IDL.Func([IDL.Text], [Survey], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVerificationStats' : IDL.Func(
        [],
        [IDL.Record({ 'verified' : IDL.Nat, 'unverified' : IDL.Nat })],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitSurvey' : IDL.Func([Survey], [], []),
    'verifyOTP' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };