/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'banking' : null } |
  { 'aadhaar' : null } |
  { 'insurance' : null };
export type ExternalBlob = Uint8Array;
export interface OTPAttempt {
  'timestamp' : bigint,
  'success' : boolean,
  'phoneNumber' : string,
}
export type OTPStatus = { 'verified' : null } |
  { 'expired' : null } |
  { 'pending' : null };
export interface SMSPayload {
  'messageType' : { 'otp' : null } |
    { 'confirmation' : null },
  'message' : string,
  'timestamp' : bigint,
  'phoneNumber' : string,
}
export interface Survey {
  'id' : string,
  'age' : bigint,
  'otp' : string,
  'modeOfPayment' : string,
  'overseasWork' : boolean,
  'incomeTaxPayer' : boolean,
  'keepsMoneyInAccount' : boolean,
  'insuranceType' : [] | [string],
  'healthInsurance' : [] | [boolean],
  'usesPaymentApps' : boolean,
  'otherEducation' : [] | [string],
  'accidentalInsurance' : [] | [boolean],
  'voterIdImage' : [] | [ExternalBlob],
  'ownsLaptop' : boolean,
  'rechargeAmount' : [] | [string],
  'postpaidAccount' : string,
  'averageDailyUsage' : string,
  'passport' : boolean,
  'hourlyRate' : string,
  'ableToPayThroughApp' : [] | [boolean],
  'insuranceDetails' : [] | [string],
  'workingDaysLowReason' : string,
  'otherDevice' : string,
  'speaksEnglish' : boolean,
  'iosSmartphone' : [] | [boolean],
  'yearsOfExperienceGroup' : string,
  'panchayat' : string,
  'ableToDoVideoCall' : boolean,
  'servingArea' : [] | [string],
  'servingCity' : [] | [string],
  'remainingBalance' : string,
  'employerName' : [] | [string],
  'usesSmartphone' : boolean,
  'timestamp' : bigint,
  'paidDuringCovid' : boolean,
  'category' : Category,
  'lifeInsurance' : [] | [boolean],
  'mostlyUsedApps' : [] | [string],
  'aadhaarHash' : [] | [string],
  'block' : string,
  'servingPincode' : [] | [string],
  'hasTradingAccount' : boolean,
  'pfEsi' : [] | [string],
  'internetConnection' : string,
  'overtimeMoney' : [] | [string],
  'phoneNumber' : string,
  'primaryWorkLocation' : string,
  'otpStatus' : OTPStatus,
  'usesBankApps' : boolean,
  'servingState' : [] | [string],
  'ableToMail' : [] | [boolean],
  'ableToUseApp' : [] | [boolean],
  'employerGivesAccommodation' : string,
  'educationLevel' : string,
  'usesMobileData' : boolean,
  'followsRegulations' : boolean,
  'phoneType' : string,
  'rechargeType' : [] | [string],
  'monthlyIncome' : string,
  'servingPanchayat' : [] | [string],
  'hasBusinessAccounts' : boolean,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'exportSurveyData' : ActorMethod<[], Array<Survey>>,
  'generateOTP' : ActorMethod<[string], string>,
  'getAllSurveys' : ActorMethod<[], Array<Survey>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategoryAnalytics' : ActorMethod<[], Array<[Category, bigint]>>,
  'getCompletionStats' : ActorMethod<
    [],
    { 'total' : bigint, 'rate' : number, 'completed' : bigint }
  >,
  'getOTPLogs' : ActorMethod<[[] | [string]], Array<OTPAttempt>>,
  'getSMSPayloads' : ActorMethod<[[] | [string]], Array<SMSPayload>>,
  'getSurvey' : ActorMethod<[string], Survey>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVerificationStats' : ActorMethod<
    [],
    { 'verified' : bigint, 'unverified' : bigint }
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitSurvey' : ActorMethod<[Survey], undefined>,
  'verifyOTP' : ActorMethod<[string, string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];