/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface OTPAttempt {
    timestamp: bigint;
    success: boolean;
    phoneNumber: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Survey {
    id: string;
    age: bigint;
    otp: string;
    modeOfPayment: string;
    insuranceType?: string;
    digitalSignature?: ExternalBlob;
    yearsOfExperienceGroup: string;
    panchayat: string;
    servingArea?: string;
    servingCity?: string;
    employerName?: string;
    timestamp: bigint;
    category: Category;
    aadhaarHash?: string;
    block: string;
    servingPincode?: string;
    phoneNumber: string;
    otpStatus: OTPStatus;
    servingPanchayat?: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface UserProfile {
    name: string;
}
export interface SMSPayload {
    messageType: Variant_otp_confirmation;
    message: string;
    timestamp: bigint;
    phoneNumber: string;
}
export enum Category {
    banking = "banking",
    aadhaar = "aadhaar",
    insurance = "insurance"
}
export enum OTPStatus {
    verified = "verified",
    expired = "expired",
    pending = "pending"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_otp_confirmation {
    otp = "otp",
    confirmation = "confirmation"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    exportSurveyData(): Promise<Array<Survey>>;
    generateOTP(phoneNumber: string): Promise<string>;
    getAllSurveys(): Promise<Array<Survey>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCategoryAnalytics(): Promise<Array<[Category, bigint]>>;
    getCompletionStats(): Promise<{
        total: bigint;
        rate: number;
        completed: bigint;
    }>;
    getOTPLogs(phoneNumber: string | null): Promise<Array<OTPAttempt>>;
    getSMSPayloads(phoneNumber: string | null): Promise<Array<SMSPayload>>;
    getSurvey(id: string): Promise<Survey>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVerificationStats(): Promise<{
        verified: bigint;
        unverified: bigint;
    }>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitSurvey(survey: Survey): Promise<void>;
    verifyOTP(phoneNumber: string, otp: string, surveyId: string): Promise<boolean>;
}
import type { Category as _Category, ExternalBlob as _ExternalBlob, OTPStatus as _OTPStatus, SMSPayload as _SMSPayload, Survey as _Survey, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async exportSurveyData(): Promise<Array<Survey>> {
        if (this.processError) {
            try {
                const result = await this.actor.exportSurveyData();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportSurveyData();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateOTP(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateOTP(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateOTP(arg0);
            return result;
        }
    }
    async getAllSurveys(): Promise<Array<Survey>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSurveys();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSurveys();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategoryAnalytics(): Promise<Array<[Category, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategoryAnalytics();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategoryAnalytics();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompletionStats(): Promise<{
        total: bigint;
        rate: number;
        completed: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompletionStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompletionStats();
            return result;
        }
    }
    async getOTPLogs(arg0: string | null): Promise<Array<OTPAttempt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOTPLogs(to_candid_opt_n25(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOTPLogs(to_candid_opt_n25(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getSMSPayloads(arg0: string | null): Promise<Array<SMSPayload>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSMSPayloads(to_candid_opt_n25(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSMSPayloads(to_candid_opt_n25(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSurvey(arg0: string): Promise<Survey> {
        if (this.processError) {
            try {
                const result = await this.actor.getSurvey(arg0);
                return from_candid_Survey_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSurvey(arg0);
            return from_candid_Survey_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVerificationStats(): Promise<{
        verified: bigint;
        unverified: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getVerificationStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVerificationStats();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitSurvey(arg0: Survey): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitSurvey(await to_candid_Survey_n30(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitSurvey(await to_candid_Survey_n30(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async verifyOTP(arg0: string, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyOTP(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyOTP(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_Category_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_OTPStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OTPStatus): OTPStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_SMSPayload_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SMSPayload): SMSPayload {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
async function from_candid_Survey_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Survey): Promise<Survey> {
    return await from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    age: bigint;
    otp: string;
    modeOfPayment: string;
    insuranceType: [] | [string];
    digitalSignature: [] | [_ExternalBlob];
    yearsOfExperienceGroup: string;
    panchayat: string;
    servingArea: [] | [string];
    servingCity: [] | [string];
    employerName: [] | [string];
    timestamp: bigint;
    category: _Category;
    aadhaarHash: [] | [string];
    block: string;
    servingPincode: [] | [string];
    phoneNumber: string;
    otpStatus: _OTPStatus;
    servingPanchayat: [] | [string];
}): Promise<{
    id: string;
    age: bigint;
    otp: string;
    modeOfPayment: string;
    insuranceType?: string;
    digitalSignature?: ExternalBlob;
    yearsOfExperienceGroup: string;
    panchayat: string;
    servingArea?: string;
    servingCity?: string;
    employerName?: string;
    timestamp: bigint;
    category: Category;
    aadhaarHash?: string;
    block: string;
    servingPincode?: string;
    phoneNumber: string;
    otpStatus: OTPStatus;
    servingPanchayat?: string;
}> {
    return {
        id: value.id,
        age: value.age,
        otp: value.otp,
        modeOfPayment: value.modeOfPayment,
        insuranceType: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.insuranceType)),
        digitalSignature: record_opt_to_undefined(await from_candid_opt_n14(_uploadFile, _downloadFile, value.digitalSignature)),
        yearsOfExperienceGroup: value.yearsOfExperienceGroup,
        panchayat: value.panchayat,
        servingArea: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.servingArea)),
        servingCity: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.servingCity)),
        employerName: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.employerName)),
        timestamp: value.timestamp,
        category: from_candid_Category_n16(_uploadFile, _downloadFile, value.category),
        aadhaarHash: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.aadhaarHash)),
        block: value.block,
        servingPincode: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.servingPincode)),
        phoneNumber: value.phoneNumber,
        otpStatus: from_candid_OTPStatus_n18(_uploadFile, _downloadFile, value.otpStatus),
        servingPanchayat: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.servingPanchayat))
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    messageType: {
        otp: null;
    } | {
        confirmation: null;
    };
    message: string;
    timestamp: bigint;
    phoneNumber: string;
}): {
    messageType: Variant_otp_confirmation;
    message: string;
    timestamp: bigint;
    phoneNumber: string;
} {
    return {
        messageType: from_candid_variant_n29(_uploadFile, _downloadFile, value.messageType),
        message: value.message,
        timestamp: value.timestamp,
        phoneNumber: value.phoneNumber
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_tuple_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_Category, bigint]): [Category, bigint] {
    return [
        from_candid_Category_n16(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    banking: null;
} | {
    aadhaar: null;
} | {
    insurance: null;
}): Category {
    return "banking" in value ? Category.banking : "aadhaar" in value ? Category.aadhaar : "insurance" in value ? Category.insurance : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    verified: null;
} | {
    expired: null;
} | {
    pending: null;
}): OTPStatus {
    return "verified" in value ? OTPStatus.verified : "expired" in value ? OTPStatus.expired : "pending" in value ? OTPStatus.pending : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    otp: null;
} | {
    confirmation: null;
}): Variant_otp_confirmation {
    return "otp" in value ? Variant_otp_confirmation.otp : "confirmation" in value ? Variant_otp_confirmation.confirmation : value;
}
async function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Survey>): Promise<Array<Survey>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Survey_n11(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_Category, bigint]>): Array<[Category, bigint]> {
    return value.map((x)=>from_candid_tuple_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SMSPayload>): Array<SMSPayload> {
    return value.map((x)=>from_candid_SMSPayload_n27(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n34(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_OTPStatus_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OTPStatus): _OTPStatus {
    return to_candid_variant_n36(_uploadFile, _downloadFile, value);
}
async function to_candid_Survey_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Survey): Promise<_Survey> {
    return await to_candid_record_n31(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    age: bigint;
    otp: string;
    modeOfPayment: string;
    insuranceType?: string;
    digitalSignature?: ExternalBlob;
    yearsOfExperienceGroup: string;
    panchayat: string;
    servingArea?: string;
    servingCity?: string;
    employerName?: string;
    timestamp: bigint;
    category: Category;
    aadhaarHash?: string;
    block: string;
    servingPincode?: string;
    phoneNumber: string;
    otpStatus: OTPStatus;
    servingPanchayat?: string;
}): Promise<{
    id: string;
    age: bigint;
    otp: string;
    modeOfPayment: string;
    insuranceType: [] | [string];
    digitalSignature: [] | [_ExternalBlob];
    yearsOfExperienceGroup: string;
    panchayat: string;
    servingArea: [] | [string];
    servingCity: [] | [string];
    employerName: [] | [string];
    timestamp: bigint;
    category: _Category;
    aadhaarHash: [] | [string];
    block: string;
    servingPincode: [] | [string];
    phoneNumber: string;
    otpStatus: _OTPStatus;
    servingPanchayat: [] | [string];
}> {
    return {
        id: value.id,
        age: value.age,
        otp: value.otp,
        modeOfPayment: value.modeOfPayment,
        insuranceType: value.insuranceType ? candid_some(value.insuranceType) : candid_none(),
        digitalSignature: value.digitalSignature ? candid_some(await to_candid_ExternalBlob_n32(_uploadFile, _downloadFile, value.digitalSignature)) : candid_none(),
        yearsOfExperienceGroup: value.yearsOfExperienceGroup,
        panchayat: value.panchayat,
        servingArea: value.servingArea ? candid_some(value.servingArea) : candid_none(),
        servingCity: value.servingCity ? candid_some(value.servingCity) : candid_none(),
        employerName: value.employerName ? candid_some(value.employerName) : candid_none(),
        timestamp: value.timestamp,
        category: to_candid_Category_n33(_uploadFile, _downloadFile, value.category),
        aadhaarHash: value.aadhaarHash ? candid_some(value.aadhaarHash) : candid_none(),
        block: value.block,
        servingPincode: value.servingPincode ? candid_some(value.servingPincode) : candid_none(),
        phoneNumber: value.phoneNumber,
        otpStatus: to_candid_OTPStatus_n35(_uploadFile, _downloadFile, value.otpStatus),
        servingPanchayat: value.servingPanchayat ? candid_some(value.servingPanchayat) : candid_none()
    };
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    banking: null;
} | {
    aadhaar: null;
} | {
    insurance: null;
} {
    return value == Category.banking ? {
        banking: null
    } : value == Category.aadhaar ? {
        aadhaar: null
    } : value == Category.insurance ? {
        insurance: null
    } : value;
}
function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OTPStatus): {
    verified: null;
} | {
    expired: null;
} | {
    pending: null;
} {
    return value == OTPStatus.verified ? {
        verified: null
    } : value == OTPStatus.expired ? {
        expired: null
    } : value == OTPStatus.pending ? {
        pending: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
